spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/dbsis
spring.datasource.username=root
# password is "root" if in workbench, leave empty if in xampp
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

security.config.allowed.urls=*
security.config.allowed.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
security.config.allowed.headers=*

spring.web.error.include-stacktrace=never
server.port=8080

jwt.secret.key=dd2f58aa73a2d3438a775d4210f44236cfd31e695205e0675994fea1ed149f84
#change to 1 min for testing (milliseconds)= 60000
jwt.secret.expiration=10800000 
